development:
  client_id: '425715198288-n3pt1hmhs99gdh11sn5frc1thqpcmemi.apps.googleusercontent.com'
  client_secret: 'iEpR1y-EmCLgx6anKfVcfLxk'

test:
  client_id: '425715198288-n3pt1hmhs99gdh11sn5frc1thqpcmemi.apps.googleusercontent.com'
  client_secret: 'iEpR1y-EmCLgx6anKfVcfLxk'

staging:
  client_id: '425715198288-n3pt1hmhs99gdh11sn5frc1thqpcmemi.apps.googleusercontent.com'
  client_secret: 'iEpR1y-EmCLgx6anKfVcfLxk'

production:
  client_id: '425715198288-n3pt1hmhs99gdh11sn5frc1thqpcmemi.apps.googleusercontent.com'
  client_secret: 'iEpR1y-EmCLgx6anKfVcfLxk'
